# Generated by Django 5.2.3 on 2025-06-18 06:55

from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    groups_to_create = [
        'Main Admin',
        'Full Access Admin',
        'Partial Access Admin',
    ]
    for group_name in groups_to_create:
        Group.objects.get_or_create(name=group_name)

def reverse_create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    groups_to_delete = [
        'Main Admin',
        'Full Access Admin',
        'Partial Access Admin',
    ]
    Group.objects.filter(name__in=groups_to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_servicerequest_assigned_to_and_more'),
        ('auth', '__latest__'),
    ]

    operations = [
        migrations.RunPython(create_groups, reverse_create_groups),
    ]
