# Generated by Django 5.2.3 on 2025-06-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_create_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('awaiting_payment', 'Awaiting Payment'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('cancelled', 'Cancelled')], default='pending_approval', max_length=20),
        ),
    ]
